v = input('Digite um valor: ')
print('O tipo do valor digitado é: {}'.format(type(v)))
print('O valor é alfabetico? {}.'.format(v.isalpha()))
print('O Valor é numerico? {}.'.format(v.isnumeric()))
print('O valor é alfanumerico? {}.'.format(v.isalnum()))
print('O valor está em letras maiuscula? {}.'.format(v.isupper()))
print('O valor está em letras minusculas? {}.'.format(v.islower()))
print('O valor está captalizado? {}.'.format(v.istitle()))
print('O valor é somente espaços? {}.'.format(v.isspace()))
