print('--- Loja do seu Chico ---')
preço = float(input('Qual o valor total de sua compra? R$'))
print('''
Escolha a forma de pagamento:
[1] - À vista no dinheiro ou cheque (10% de desconto)
[2] - À vista no cartão              (5% de desconto)
[3] - Parcelado no cartão          (Até 2x sem juros)
''')
forma = int(input('Digite o número correspondente à sua forma de pagamento: '))
print('')
if forma == 1:
    desconto = (preço * 0.10)
    print('À vista no dinheiro ou cheque')
    print('-'*25)
    print('Nota fiscal:\n')
    print('Produtos:        R${:^.2f}'.format(preço))
    print('Desconto(10%):   R${:^.2f}'.format(desconto))
    print('\nTotal:           R${:^.2f}'.format(preço-desconto))
elif forma == 2:
    desconto = (preço * 0.05)
    print('   À vista no cartão')
    print('-'*25)
    print('Nota fiscal:\n')
    print('Produtos:        R${:^.2f}'.format(preço))
    print('Desconto(5%):    R${:^.2f}'.format(desconto))
    print('\nTotal:           R${:^.2f}'.format(preço-desconto))
elif forma == 3:
    print('Parcelado no cartão de crédito.')
    print('\nOBS: Ao parcelar em mais de 3x o juros será de 20%.')
    nparcelas = int(input('\nEm quantas vezes você quer parcelar? '))
    if nparcelas >= 3:
        juros = (preço * 0.20)
        print('  Parcelado no cartão')
        print('-'*25)
        print('Nota fiscal:\n')
        print('Produtos:        R${:^.2f}'.format(preço))
        print('Juros(20%):      R${:^.2f}'.format(juros))
        print('Parcelas:        R${:^.2f}'.format((preço+juros)/nparcelas))
        print('            {}x com juros'.format(nparcelas))
        print('\nTotal:           R${:^.2f}'.format(preço+juros))
    else:
        juros = 0
        print('  Parcelado no cartão')
        print('-'*25)
        print('Nota fiscal:\n')
        print('Produtos:        R${:^.2f}'.format(preço))
        print('Juros(0%):       R${:^.2f}'.format(juros))
        print('Parcelas:        R${:^.2f}'.format((preço+juros)/nparcelas))
        print('            {}x sem juros'.format(nparcelas))
        print('\nTotal:           R${:^.2f}'.format(preço+juros))
else:
    print('\nEssa opção não existe, tente novamente.')
print('\n      Volte Sempre!')
print('-'*25)
